name       : volume_key
version    : 0.3.9
release    : 1
source     :
    - https://releases.pagure.org/volume_key/volume_key-0.3.9.tar.xz : 450a54fe9bf56acec6850c1e71371d3e4913c9ca1ef0cdc3a517b4b6910412a6
license    : GPL-2.0
component  : system.utils
summary    : An utility for manipulating storage encryption keys and passphrases
description: |
    This package provides a command-line tool for manipulating storage volume
    encryption keys and storing them separately from volumes.
    
    The main goal of the software is to allow restoring access to an encrypted
    hard drive if the primary user forgets the passphrase.  The encryption key
    back up can also be useful for extracting data after a hardware or software
    failure that corrupts the header of the encrypted volume, or to access the
    company data after an employee leaves abruptly.
builddeps  :
    - pkgconfig(libcryptsetup)
    - pkgconfig(nss)
    - gpgme-devel
    - libassuan-devel
setup      : |
    %patch -p1 < $pkgfiles/volume_key-0.3.9-config.h.patch
    %patch -p1 < $pkgfiles/volume_key-0.3.9-fips-crash.patch
    %patch -p1 < $pkgfiles/volume_key-0.3.9-find_python.patch
    %reconfigure PYTHON=python3
build      : |
    %make
install    : |
    %make_install
